apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtsp.fullname" . }}
  labels:
    {{- include "rtsp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if hasKey .Values.service "nodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rtsp.selectorLabels" . | nindent 4 }}
